version: '3.8'

services:
  db:
    image: postgres:13
    container_name: flask_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vesna
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    networks:
      - mynetwork
    restart: always

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
