version: '3.8'

services:
  db:
    image: postgres:13
    container_name: flask_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vesna
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    networks:
      - mynetwork
    restart: always

  flask_app:
    build: .
    container_name: flask_app
    depends_on:
      - db
    environment:
      FLASK_APP: wsgi.py
      FLASK_ENV: production
      DATABASE_URL: postgresql://root:root@db:5432/vesna
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    restart: always
    volumes:
      - ./static/uploads:/app/static/uploads

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    restart: always

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge