version: '3.3'

services:
  # Front container (node + npm)
  front:
    image: ghcr.io/j1sk1ss/vesna-front-env:0.1v
    ports:
      - 80:80
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./front
        target: /var/www/it-vesna/body
    command: npm start --prefix body/site-body

  # Back container (Python + libs)
  server:
    image: ghcr.io/j1sk1ss/vesna-back-env:0.1v
    ports:
      - 5000:5000
    command: python server.py
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /var/www/it-vesna/server

  # Data base
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 28072003
      POSTGRES_USER: root
      POSTGRES_DB: it-vesna-db

  # Data base GUI in web
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db:
