version: '3.3'
# TODO: Choose another ports. We take to large distance detween services
services:
  # Front container (node + npm)
  front:
    image: ghcr.io/j1sk1ss/vesna-front-env:0.1v
    ports:
      - 80:3000
    depends_on:
      - pages-service
      - users-db-service
    volumes:
      - type: bind
        source: ./front
        target: /var/www/it-vesna/body
    command: npm start --prefix body/site-body

  # Back container (Python + libs)
  pages-service:
    image: ghcr.io/j1sk1ss/vesna-back-env:0.2v
    ports:
      - 5400:5400
    command: python service.py
    depends_on:
      - api-service
    volumes:
      - type: bind
        source: ./back/pages_service
        target: /var/www/it-vesna/server

  # API container (Python + libs)
  api-service:
    image: ghcr.io/j1sk1ss/vesna-back-env:0.2v
    ports:
      - 5000:5000
    command: python service.py
    depends_on:
      - users-db
      - mail-service
      - crypto-service
      - users-db-service
    volumes:
      - type: bind
        source: ./back/api_service
        target: /var/www/it-vesna/server

  # Mail container
  mail-service:
    image: ghcr.io/j1sk1ss/vesna-back-env:0.2v
    ports:
      - 5200:5200
    command: python service.py
    depends_on:
      - users-db
    volumes:
      - type: bind
        source: ./back/mail_service
        target: /var/www/it-vesna/server

  # Crypto container
  crypto-service:
    image: ghcr.io/j1sk1ss/vesna-back-env:0.2v
    ports:
      - 5300:5300
    command: python service.py
    depends_on:
      - users-db
    volumes:
      - type: bind
        source: ./back/crypto_service
        target: /var/www/it-vesna/server

  # =================
  # USERS MICROSERVICE

  users-db-service:
    image: ghcr.io/j1sk1ss/vesna-back-env:0.2v
    ports:
      - 5100:5100
    command: python service.py
    depends_on:
      - users-db
    volumes:
      - type: bind
        source: ./back/db_service
        target: /var/www/it-vesna/server

  users-db:
    image: postgres
    ports:
      - 5101:5432
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 28072003
      POSTGRES_USER: root
      POSTGRES_DB: it-vesna-db
    volumes:
      - ./back/users_service/init.sql:/docker-entrypoint-initdb.d/init.sql

  # =================
  # POSTS MICROSERVICE

  posts-db-service:
    image: ghcr.io/j1sk1ss/vesna-back-env:0.2v
    ports:
      - 5600:5600
    command: python service.py
    depends_on:
      - users-db
    volumes:
      - type: bind
        source: ./back/posts_service
        target: /var/www/it-vesna/server

  posts-db:
    image: postgres
    ports:
      - 5601:5432
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 28072003
      POSTGRES_USER: root
      POSTGRES_DB: it-vesna-db
    volumes:
      - ./back/posts_service/init.sql:/docker-entrypoint-initdb.d/init.sql

  # =================
  # REQUESTS MICROSERVICE

  requests-db-service:
    image: ghcr.io/j1sk1ss/vesna-back-env:0.2v
    ports:
      - 5700:5700
    command: python service.py
    depends_on:
      - users-db
    volumes:
      - type: bind
        source: ./back/posts_service
        target: /var/www/it-vesna/server

  requests-db:
    image: postgres
    ports:
      - 5701:5432
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 28072003
      POSTGRES_USER: root
      POSTGRES_DB: it-vesna-db
    volumes:
      - ./back/requests_service/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Data base GUI in web
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - users-db

networks:
  default:
    name: it-vesna-network