version: '3.3'


services:
  # Front container (node + npm)
  front:
    build: front/.
    ports:
      - 80:80
    command: npm start
    depends_on:
      - server

  # Back container (Python + libs)
  server:
    build: server/.
    ports:
      - 5000:5000
    command: python ./server/server.py
    depends_on:
      - db

  # Data base
  db:
    image: postgres
    restart: always

    # set shared memory limit when using docker-compose
    shm_size: 128mb

    # Db
    environment:
      POSTGRES_PASSWORD: 28072003
      POSTGRES_USER: root
      POSTGRES_DB: it-vesna-db

  # Data base GUI in web
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
